version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: clone-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: clone_admin
      MONGO_INITDB_ROOT_PASSWORD: clone_pass
      MONGO_INITDB_DATABASE: clone_os
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: clone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:v1.15
    container_name: clone-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: clone-minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  redis_data:
  minio_data:
