"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INITIAL_INTEGRATION_CATALOG = void 0;
exports.INITIAL_INTEGRATION_CATALOG = [
    {
        id: "github",
        name: "GitHub",
        category: "Engineering",
        description: "Code repositories, pull requests, issue tracking, and branch management.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
        popular: true,
        capabilitiesCount: 5,
    },
    {
        id: "codespaces",
        name: "GitHub Codespaces",
        category: "Cloud infrastructure",
        description: "Cloud container sandbox environments for AI developer task execution.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
        popular: false,
        capabilitiesCount: 4,
    },
    {
        id: "slack",
        name: "Slack",
        category: "Communication",
        description: "Real-time team messaging, progress alerts, and channel notifications.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/slack/slack-original.svg",
        popular: true,
        capabilitiesCount: 4,
    },
    {
        id: "gmail",
        name: "Gmail",
        category: "Communication",
        description: "Customer inbox monitoring, draft email creation, and email broadcasting.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg",
        popular: true,
        capabilitiesCount: 3,
    },
    {
        id: "calendar",
        name: "Google Calendar",
        category: "Productivity",
        description: "Executive meeting scheduling, calendar sync, and availability checking.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg",
        popular: false,
        capabilitiesCount: 3,
    },
    {
        id: "gdrive",
        name: "Google Drive",
        category: "Storage",
        description: "Shared document storage, asset management, and company file indexing.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg",
        popular: false,
        capabilitiesCount: 3,
    },
    {
        id: "notion",
        name: "Notion",
        category: "Productivity",
        description: "Knowledge base indexing, product specs, and organizational wikis.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/notion/notion-original.svg",
        popular: true,
        capabilitiesCount: 4,
    },
    {
        id: "linear",
        name: "Linear",
        category: "Project management",
        description: "Issue tracking, cycle planning, and project roadmap synchronization.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linear/linear-original.svg",
        popular: true,
        capabilitiesCount: 4,
    },
    {
        id: "discord",
        name: "Discord",
        category: "Communication",
        description: "Community channel announcements, event notifications, and bot interactions.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/discord/discord-original.svg",
        popular: false,
        capabilitiesCount: 3,
    },
    {
        id: "intercom",
        name: "Intercom",
        category: "Customer support",
        description: "Live chat customer support management and ticket routing.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/intercom/intercom-original.svg",
        popular: true,
        capabilitiesCount: 3,
    },
    {
        id: "zendesk",
        name: "Zendesk",
        category: "Customer support",
        description: "Enterprise customer service ticketing and knowledge base integration.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/zendesk/zendesk-original.svg",
        popular: false,
        capabilitiesCount: 3,
    },
    {
        id: "hubspot",
        name: "HubSpot",
        category: "CRM",
        description: "Sales lead tracking, customer contact management, and deal stages.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hubspot/hubspot-original.svg",
        popular: true,
        capabilitiesCount: 4,
    },
    {
        id: "stripe",
        name: "Stripe",
        category: "Finance",
        description: "Customer billing inspection, subscription statuses, and revenue tracking.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/stripe/stripe-original.svg",
        popular: true,
        capabilitiesCount: 3,
    },
    {
        id: "sentry",
        name: "Sentry",
        category: "Analytics",
        description: "Application error monitoring, bug stack traces, and crash alert routing.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sentry/sentry-original.svg",
        popular: false,
        capabilitiesCount: 2,
    },
    {
        id: "vercel",
        name: "Vercel",
        category: "Cloud infrastructure",
        description: "Frontend deployment monitoring, preview URL inspection, and domain settings.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg",
        popular: true,
        capabilitiesCount: 3,
    },
    {
        id: "coder",
        name: "Coder",
        category: "Cloud infrastructure",
        description: "Self-hosted developer workspaces and remote Linux dev environments.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/coder/coder-original.svg",
        popular: false,
        capabilitiesCount: 3,
    },
    {
        id: "daytona",
        name: "Daytona",
        category: "Cloud infrastructure",
        description: "Open source development environment manager for AI code executions.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/daytona/daytona-original.svg",
        popular: false,
        capabilitiesCount: 3,
    },
    {
        id: "e2b",
        name: "E2B",
        category: "Cloud infrastructure",
        description: "Secure sandboxed cloud environments for running code & LLM tools.",
        iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/e2b/e2b-original.svg",
        popular: true,
        capabilitiesCount: 3,
    },
];
//# sourceMappingURL=catalog.js.map